### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by bullik01** [FolfyBlue/GetFreeGames#1]
Hi! Can you add explanation to README what is it? It's plugin for ASF or standalone script using ASF?

**Comment by JoshuaVandaele** [comment]
Standalone script using ASF's IPC API

**Comment by JoshuaVandaele** [comment]
Fixed in https://github.com/FolfyBlue/GetFreeGames/commit/6b128eaa58fee6559ce1cd3331e005dbb39de500
