### ISSUE TITLE
Is it still working ? I can't see the games being added

### ISSUE THREAD

**Issue by Denver3D** [FolfyBlue/GetFreeGames#4]
dear team

First thank you so much for your hard work but I was wondering if it's still working ? I've left it for one hour and can't see the games being added

**Comment by JoshuaVandaele** [comment]
It first goes on a game collecting spree then once done adds them all to the account, which can take quite a while. As if it still works, no idea, haven't used it in ages

**Comment by HerXayah** [comment]
![image](https://user-images.githubusercontent.com/45071533/107149792-f72fa500-695a-11eb-8c6a-9004772c1013.png)
will loop there for me
