### ISSUE TITLE
Looping on last few games.

### ISSUE THREAD

**Issue by HerXayah** [FolfyBlue/GetFreeGames#6]
![image](https://user-images.githubusercontent.com/45071533/107149813-19292780-695b-11eb-87ef-79ce8215af8e.png)
This happens for me after 5 days. itll loop there

**Comment by HerXayah** [comment]
Small Info i have both ArchiSteamFarm and the Script running via PM2
![image](https://user-images.githubusercontent.com/45071533/107150327-948bd880-695d-11eb-953b-f7eb299be97c.png)

**Comment by JoshuaVandaele** [comment]
I am unable to reproduce this, do you have any clues as to why or how it happens?

**Comment by HerXayah** [comment]
> I am unable to reproduce this, do you have any clues as to why or how it happens?

Nopers

**Comment by JoshuaVandaele** [comment]
I've submitted a few minor fixes which might help with the problem, but nothing is guarenteed since I still don't know why it happens

**Comment by JoshuaVandaele** [comment]
Create a new issue if it happens again, thanks for your help
